# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SportQuest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SportQuest

  target 'SportQuestTests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'TextFieldEffects'
pod 'DWAnimatedLabel'
pod 'WCLShineButton'
pod 'Charts'
pod 'BetterSegmentedControl'
pod 'MarqueeLabel'
pod "AGCircularPicker"
pod 'SwiftGifOrigin'
pod 'AMTabView'
end
